### ISSUE TITLE
[Repo request]: Add Cassandra Salt Extension 

### ISSUE THREAD

**Issue by dmurphy18** [salt-extensions/community#17]
Used salt-extension-copier to extract Cassandra from current Salt 3007.x branch and generated a salt extension, which I now want to have added to the https://github.com/salt-extensions repositories for continuing future development.

That and test drive this Repo Request process

**Comment by max-arnold** [comment]
Created the repo https://github.com/salt-extensions/saltext-cassandra and invited you to this github org as an owner (because you are the WG captain)

Questions about the whole process:

1. Should we require a link to an existing repository that is going to be promoted to Salt Extensions GH org? Or it is ok to start from an empty repo?
2. Can we actually grant a repository maintainer rights to anyone, until we enable Trusted Publishing on PyPI?
3. Does the Cassandra extension belong to community modules or it is a part of extended core? The lists are confusing, because the extended core one contains unit tests https://github.com/saltstack/great-module-migration/blob/main/core-ext-modules.txt#L202 and the community one contains the modules https://github.com/saltstack/great-module-migration/blob/main/community-ext-modules.txt#L147.   If it belongs to extended core, then according to SEP (and also from the supply chain security considerations) it should be hosted in the `saltstack` org: `Supported modules will be moved to their own repositories within the SaltStack Github organization where they can be maintained separately from the Salt codebase.`

**Comment by dmurphy18** [comment]
Moved the code into the repo, thanks for the repo.  Will address the questions when return from vacation on Tuesday

**Comment by dmurphy18** [comment]
@max-arnold Soory for talking time to get back to you on your questions, snowed under with a small team :)

Answers:
1. I think we should require pulling from Salt for a Salt Extension if that functionality already exists in Salt, as a starting point.  If the functionality doesn't exist in Salt, then an empty repo is fine, but it must conform, that is, Code of Conduct, docs, etc.
2. Think after the WG mtg on 5th Sept., need to discuss this with @nicholasmhughes , but I am in favor of repository maintainer only gets rights for their repository (unless they also have other roles, such as yourself or @lkubb), especially with respect to Trusted Publishing.
3. I favor having them all under salt-extensions, since this will keep core and community extensions functioning with the same tools, and improvements. But you raise a good point, Broadcom may have different opinions and want them under SaltStack.org. I will check up the management chain as to their decision.
